name: Terraform PLAN on Solomon Williams Rke2 Downstream Dev Cluster
on:
  push:
    branches:
      - main
  pull_request:

  workflow_dispatch:
    inputs:
      terraform-plan-rke2-downstream-dev:
        description: "Do You Want To Terraform PLAN Solomon Williams Rke2 Downstream Dev Cluster (yes/no)"
        required: true
        default: "no"
        type: choice
        options:
          - "yes"
          - "no"

env:
  AWS_ACCOUNT_NUMBER: 505648753038
  GITHUB_TOKEN: ${{ secrets.G_PAT }}
permissions: write-all

jobs:
  terraform-plan-rke2-downstream-dev:
    name: Rke2 Downstream Dev Cluster Terraform Plan
    if: github.event_name == 'workflow_dispatch' || github.event_name == 'pull_request' || github.event_name == 'push' || github.event.inputs.terraform-plan-rke2-downstream-dev == 'yes'
    uses: kendops/terraform-gha-aws-oidc-config/.github/workflows/terraform-base.yml@main
    secrets: inherit
    with:
      stage: rke2-downstream-dev
      iam_role: "arn:aws:iam::505648753038:role/terraform-gha-oidc-role"
      tf_mode: "plan-destroy"
      # tf_workspace: "rke2-downstream-dev"
      environment_directory: solomon-rke2-downstream-cluster
      aws_region: "us-east-2"

  rke2-downstream-dev-plan-pir-gen:
    name: Generate PIR for Rke2 Downstream Dev Cluster on Aws
    secrets: inherit
    if: github.event_name == 'workflow_dispatch' || github.event_name == 'pull_request' || github.event_name == 'push' || github.event.inputs.terraform-plan-rke2-downstream-dev == 'yes'
    uses: kendops/terraform-gha-aws-oidc-config/.github/workflows/pir-and-ir.yml@main
    needs: terraform-plan-rke2-downstream-dev
    with:
      stage: rke2-downstream-dev
      iam_role: "arn:aws:iam::505648753038:role/terraform-gha-oidc-role"
      tf_mode: "plan-destroy"
      environment_directory: solomon-rke2-downstream-cluster
      project_name: kendops-co
      org_domain_name: kendops
      deployment_time: 8
      deployment_status: "success"
      product_name: "Rke2 Downstream Dev Cluster on Aws"
      deployment_cluster_name: "local"
      aws_account_name: "kendops-aws-oidc-account"
      code_commit_sha: ${{github.sha}}
      code_git_ref: ${{github.ref}}
      release_version: "v0.0.1"
      aws_region: "us-east-2"
      ir_s3_bucket: kendops-rke2-manager-state


