apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: production
  namespace: metallb-system
spec:
  addresses:
  - 172.29.0.174-172.29.0.178
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: l2-advert
  namespace: metallb-system

# kubectl get ipaddresspools.metallb.io -n metallb-system
# kubectl get l2advertisements.metallb.io -n metallb-system
# kubectl describe ipaddresspools.metallb.io production -n metallb-system
      
